# Generated by Django 4.0.6 on 2022-08-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prispevok', '0002_rename_post_prispevok'),
    ]

    operations = [
        migrations.AddField(
            model_name='prispevok',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
