# Generated by Django 4.0.6 on 2022-08-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prispevok', '0003_prispevok_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prispevok',
            name='slug',
        ),
    ]
