# Generated by Django 4.0.6 on 2022-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prispevok', '0004_remove_prispevok_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prispevok',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
